#!/bin/bash

# Signage System - SSL Certificate Setup Script
# This script installs Let's Encrypt SSL certificates for all domains
# Run this AFTER setup-nginx.sh and AFTER verifying HTTP access works

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=========================================="
echo "Signage System - SSL Setup"
echo "=========================================="
echo ""

# Check if running with sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run with sudo${NC}"
    echo "Usage: sudo bash docker/setup-ssl.sh"
    exit 1
fi

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Check if .env exists
if [ ! -f "$PROJECT_ROOT/.env" ]; then
    echo -e "${RED}Error: .env file not found!${NC}"
    exit 1
fi

# Load environment variables
echo -e "${GREEN}✓${NC} Loading environment variables from .env"
set -a
source "$PROJECT_ROOT/.env"
set +a

# Validate required variables
if [ -z "$API_DOMAIN" ] || [ -z "$ADMIN_DOMAIN" ] || [ -z "$PLAYER_DOMAIN" ]; then
    echo -e "${RED}Error: Domain variables not set in .env${NC}"
    exit 1
fi

if [ -z "$SSL_EMAIL" ]; then
    echo -e "${RED}Error: SSL_EMAIL not set in .env${NC}"
    echo "Please set your email for Let's Encrypt notifications"
    exit 1
fi

echo ""
echo "SSL Configuration:"
echo "  Email: $SSL_EMAIL"
echo "  Domains:"
echo "    - $ADMIN_DOMAIN"
echo "    - $API_DOMAIN"
echo "    - $PLAYER_DOMAIN"
echo ""

# Warning about prerequisites
echo -e "${YELLOW}IMPORTANT: Before continuing, ensure:${NC}"
echo "  1. DNS records are propagated (test with: host $ADMIN_DOMAIN)"
echo "  2. MikroTik port forwarding is configured (ports 80, 443)"
echo "  3. HTTP access works from internet (test from mobile data)"
echo "  4. Nginx is running (sudo systemctl status nginx)"
echo ""
read -p "Have you verified all prerequisites? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Setup cancelled. Please verify prerequisites first."
    exit 0
fi

# Check if certbot is installed
if ! command -v certbot &> /dev/null; then
    echo "Certbot not installed. Installing..."
    apt-get update
    apt-get install -y certbot python3-certbot-nginx
    echo -e "${GREEN}✓${NC} Certbot installed"
else
    echo -e "${GREEN}✓${NC} Certbot already installed"
fi

# Check Nginx is running
if ! systemctl is-active --quiet nginx; then
    echo -e "${RED}Error: Nginx is not running${NC}"
    echo "Start Nginx first: sudo systemctl start nginx"
    exit 1
fi

# Stop Nginx temporarily for standalone mode (safer for initial cert)
echo ""
echo "Stopping Nginx temporarily for certificate generation..."
systemctl stop nginx

# Generate SSL certificate for all domains
echo ""
echo "Generating SSL certificates..."
echo "This may take a few minutes..."
echo ""

certbot certonly \
    --standalone \
    --non-interactive \
    --agree-tos \
    --email "$SSL_EMAIL" \
    -d "$ADMIN_DOMAIN" \
    -d "$API_DOMAIN" \
    -d "$PLAYER_DOMAIN" \
    --preferred-challenges http

if [ $? -ne 0 ]; then
    echo -e "${RED}Error: Certificate generation failed${NC}"
    echo ""
    echo "Common issues:"
    echo "  1. DNS not propagated - wait 5-30 minutes after DNS changes"
    echo "  2. Port 80 not accessible - check MikroTik port forwarding"
    echo "  3. Firewall blocking - check server firewall rules"
    echo ""
    echo "Starting Nginx again..."
    systemctl start nginx
    exit 1
fi

echo -e "${GREEN}✓${NC} SSL certificates generated"

# Update Nginx configuration to use SSL
NGINX_CONFIG="/etc/nginx/sites-available/signage"
NGINX_SSL_CONFIG="$SCRIPT_DIR/nginx/signage-ssl.conf"

echo ""
echo "Updating Nginx configuration for HTTPS..."

# Generate SSL configuration from template
cat > "$NGINX_SSL_CONFIG" <<EOF
# Signage System Nginx Configuration with SSL
# Auto-generated by setup-ssl.sh

# Backend API - ${API_DOMAIN}
server {
    listen 80;
    server_name ${API_DOMAIN};

    # Redirect to HTTPS
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${API_DOMAIN};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/${ADMIN_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${ADMIN_DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Robots-Tag "noindex, nofollow" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Client body size limit
    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE:-100M};

    # Main API proxy
    location / {
        proxy_pass http://localhost:${BACKEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # WebSocket support
    location /ws {
        proxy_pass http://localhost:${BACKEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket timeouts
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }

    # Access logs
    access_log /var/log/nginx/${API_DOMAIN}.access.log;
    error_log /var/log/nginx/${API_DOMAIN}.error.log;
}

# CMS Admin - ${ADMIN_DOMAIN}
server {
    listen 80;
    server_name ${ADMIN_DOMAIN};

    # Redirect to HTTPS
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${ADMIN_DOMAIN};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/${ADMIN_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${ADMIN_DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Client body size limit
    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE:-100M};

    location / {
        proxy_pass http://localhost:${CMS_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Access logs
    access_log /var/log/nginx/${ADMIN_DOMAIN}.access.log;
    error_log /var/log/nginx/${ADMIN_DOMAIN}.error.log;
}

# Player/Viewer - ${PLAYER_DOMAIN}
server {
    listen 80;
    server_name ${PLAYER_DOMAIN};

    # Redirect to HTTPS
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${PLAYER_DOMAIN};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/${ADMIN_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${ADMIN_DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Client body size limit
    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE:-100M};

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml+rss;

    location / {
        proxy_pass http://localhost:${PLAYER_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Access logs
    access_log /var/log/nginx/${PLAYER_DOMAIN}.access.log;
    error_log /var/log/nginx/${PLAYER_DOMAIN}.error.log;
}
EOF

# Backup old config and install new one
cp "$NGINX_CONFIG" "$NGINX_CONFIG.backup.$(date +%Y%m%d_%H%M%S)"
cp "$NGINX_SSL_CONFIG" "$NGINX_CONFIG"
echo -e "${GREEN}✓${NC} SSL configuration installed"

# Test Nginx configuration
echo ""
echo "Testing Nginx configuration..."
if nginx -t; then
    echo -e "${GREEN}✓${NC} Nginx configuration is valid"
else
    echo -e "${RED}Error: Nginx configuration test failed${NC}"
    exit 1
fi

# Start Nginx
echo ""
echo "Starting Nginx..."
systemctl start nginx
echo -e "${GREEN}✓${NC} Nginx started"

# Setup auto-renewal
echo ""
echo "Setting up automatic certificate renewal..."
if ! grep -q "certbot renew" /etc/crontab; then
    echo "0 0,12 * * * root certbot renew --quiet --post-hook 'systemctl reload nginx'" >> /etc/crontab
    echo -e "${GREEN}✓${NC} Auto-renewal configured (checks twice daily)"
else
    echo -e "${GREEN}✓${NC} Auto-renewal already configured"
fi

echo ""
echo "=========================================="
echo "SSL Setup Complete!"
echo "=========================================="
echo ""
echo "HTTPS URLs (accessible from internet):"
echo "  Admin Dashboard: https://$ADMIN_DOMAIN"
echo "  Backend API: https://$API_DOMAIN"
echo "  API Docs: https://$API_DOMAIN/docs"
echo "  Player/Display: https://$PLAYER_DOMAIN"
echo ""
echo "Certificates:"
echo "  Location: /etc/letsencrypt/live/$ADMIN_DOMAIN/"
echo "  Valid for: 90 days"
echo "  Auto-renewal: Enabled (checks twice daily)"
echo ""
echo "Next Steps:"
echo "1. Test HTTPS access from internet (use mobile data):"
echo "   curl -I https://$ADMIN_DOMAIN"
echo "   curl -I https://$API_DOMAIN/health"
echo ""
echo "2. Update environment variables if needed:"
echo "   - Set VITE_API_URL=https://$API_DOMAIN in .env"
echo "   - Set VITE_WS_URL=wss://$API_DOMAIN/ws in .env"
echo ""
echo "3. Rebuild frontend if URLs changed:"
echo "   docker-compose -f docker/docker-compose.yml up -d --build cms player"
echo ""
echo "Manual certificate renewal (if needed):"
echo "  sudo certbot renew --force-renewal"
echo "  sudo systemctl reload nginx"
echo ""
