"""
Device DTOs (Data Transfer Objects)
Request/Response models for Device API layer
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any, Literal
from datetime import datetime


# =============================================================================
# REQUEST DTOs
# =============================================================================

class RequestActivationCodeRequest(BaseModel):
    """Request activation code - called by player"""
    # 🔒 SECURITY: organization_id removed - should come from device_token JWT or be assigned during activation
    # 🚫 DO NOT allow player to send organization_id - prevents org hijacking attack
    code: str = Field(..., min_length=6, max_length=6, description="6-digit activation code generated by frontend")
    device_type: str = Field(default='monitor', pattern='^(tv|monitor)$')
    device_name: str = Field(default='New Device', max_length=200)
    device_uuid: Optional[str] = Field(None, max_length=100)
    platform: str = Field(default='browser', max_length=50)
    device_token: Optional[str] = Field(None, max_length=500)  # JWT token for re-registration


class ActivateDeviceRequest(BaseModel):
    """Activate device - called by CMS admin"""
    unique_code: str = Field(..., min_length=6, max_length=6)
    device_name: Optional[str] = Field(None, max_length=200)
    room_number: Optional[str] = Field(None, max_length=50)
    location_type: Optional[str] = Field(None, pattern='^(guest_room|lobby|conference_room|restaurant|other)$')


class HeartbeatRequest(BaseModel):
    """Heartbeat from player - sent every 30 seconds"""
    unique_code: str = Field(..., min_length=6, max_length=6)
    device_uuid: Optional[str] = None
    screen_width: Optional[int] = Field(None, gt=0)
    screen_height: Optional[int] = Field(None, gt=0)
    viewport_width: Optional[int] = Field(None, gt=0)
    viewport_height: Optional[int] = Field(None, gt=0)
    device_pixel_ratio: Optional[float] = Field(None, gt=0)
    user_agent: Optional[str] = Field(None, max_length=500)
    connection_type: Optional[str] = Field(None, max_length=50)
    connection_speed: Optional[float] = Field(None, ge=0)


class UpdateDeviceRequest(BaseModel):
    """Update device settings - called by CMS admin"""
    device_name: Optional[str] = Field(None, max_length=200)
    room_number: Optional[str] = Field(None, max_length=50)
    location_type: Optional[str] = Field(None, pattern='^(guest_room|lobby|conference_room|restaurant|other)$')
    rotation: Optional[int] = Field(None, ge=0, le=360)  # Rotation in degrees (0, 90, 180, 270)
    is_volume_enabled: Optional[bool] = None
    is_personalization_supported: Optional[bool] = None
    privacy_mode: Optional[str] = Field(None, pattern='^(none|limited|full)$')


class DeviceLogEntry(BaseModel):
    """Single log entry from player"""
    level: str = Field(..., pattern='^(log|warn|error|info)$')
    message: str = Field(..., max_length=1000)
    timestamp: str  # ISO format from player


class DeviceLogsRequest(BaseModel):
    """Batch logs from player - sent periodically"""
    device_id: int = Field(..., gt=0)
    logs: list[DeviceLogEntry] = Field(..., min_items=1, max_items=100)


class ValidateResetPasswordRequest(BaseModel):
    """Validate reset password - called by player before hard reset"""
    password: str = Field(..., min_length=1, max_length=100)


class ConnectionLogEntryDTO(BaseModel):
    """Single connection log entry from player"""
    logged_at: datetime = Field(..., description="Timestamp when event occurred on player device")
    event_type: Literal['network', 'server', 'speed_test'] = Field(..., description="Type of event")
    status: str = Field(..., max_length=20, description="Event status")
    latency_ms: Optional[int] = Field(None, ge=0, description="Network latency in milliseconds")
    error_message: Optional[str] = Field(None, max_length=1000, description="Error details if failed")
    download_speed_mbps: Optional[float] = Field(None, ge=0, description="Download speed in Mbps")
    upload_speed_mbps: Optional[float] = Field(None, ge=0, description="Upload speed in Mbps")
    metadata: Optional[Dict[str, Any]] = Field(default={}, description="Additional metadata")


class SaveConnectionLogsDTO(BaseModel):
    """Batch connection logs from player - sent every 5 minutes"""
    logs: List[ConnectionLogEntryDTO] = Field(..., min_items=1, max_items=100, description="Connection log entries")


# =============================================================================
# RESPONSE DTOs
# =============================================================================

class ActivationCodeResponse(BaseModel):
    """Activation code response - for player"""
    unique_code: str
    expires_at: str  # ISO format
    device_id: int
    device_token: Optional[str] = None  # 🔑 JWT token for re-registration (only if org assigned)

    class Config:
        from_attributes = True


class DeviceResponse(BaseModel):
    """Device response - for CMS"""
    id: int
    device_type: str
    device_name: str
    organization_id: Optional[int]  # None for unassigned devices

    # Activation info
    unique_code: Optional[str]
    code_expires_at: Optional[datetime]
    device_uuid: Optional[str]

    # Network info
    ip_address: Optional[str]
    platform: Optional[str]

    # Device metadata
    screen_width: Optional[int]
    screen_height: Optional[int]
    viewport_width: Optional[int]
    viewport_height: Optional[int]
    device_pixel_ratio: Optional[float]
    user_agent: Optional[str]
    connection_type: Optional[str]
    connection_speed: Optional[float]

    # WebOS specific
    model_name: Optional[str]
    firmware_version: Optional[str]

    # Status
    status: str
    last_seen_at: Optional[datetime]
    is_online: bool  # Computed field

    # Display settings
    rotation: int
    is_volume_enabled: bool

    # Hotel-specific
    room_number: Optional[str]
    location_type: str
    is_personalization_supported: bool
    privacy_mode: str

    # Metadata
    created_at: datetime
    updated_at: Optional[datetime]
    released_at: Optional[datetime]

    class Config:
        from_attributes = True


class DeviceActivationResponse(BaseModel):
    """Response when device is activated - includes JWT token"""
    device: DeviceResponse
    token: str = Field(..., description="JWT token for device authentication")
    message: Optional[str] = None


class DeviceListResponse(BaseModel):
    """List of devices - for CMS dashboard"""
    items: list[DeviceResponse]  # Changed from 'devices' to 'items' to match frontend
    total: int
    online: int

    class Config:
        from_attributes = True


class HeartbeatResponse(BaseModel):
    """Heartbeat response - minimal response to player"""
    success: bool = True
    message: str = "Heartbeat received"

    class Config:
        from_attributes = True


class ActivationStatusResponse(BaseModel):
    """Check activation status - for player polling"""
    activated: bool  # Player expects 'activated' not 'is_activated'
    expired: bool = False  # True if activation code has expired
    device_id: Optional[int] = None
    device_name: Optional[str] = None
    organization_id: Optional[int] = None  # For player to know which org it belongs to
    organization_pin: Optional[str] = None  # 6-digit PIN for hard reset (if org assigned)
    device_token: Optional[str] = None  # JWT token for session restore after cache clear
    unique_code: Optional[str] = None  # 6-digit activation code for heartbeat
    message: str

    class Config:
        from_attributes = True


# =============================================================================
# DEVICE COMMANDS DTOs
# =============================================================================

class DeviceCommandCreate(BaseModel):
    """Create device command - called by CMS"""
    command_type: str = Field(..., pattern='^(reboot|refresh_content|update_settings|clear_cache|screenshot|update_playlist)$')
    command_data: Optional[dict] = Field(default={})
    priority: int = Field(default=5, ge=1, le=10)
    expires_in_minutes: int = Field(default=60, ge=5, le=1440)


class BulkDeviceCommandCreate(BaseModel):
    """Create command for multiple devices"""
    device_ids: list[int] = Field(..., min_items=1, max_items=100)
    command_type: str = Field(..., pattern='^(reboot|refresh_content|update_settings|clear_cache|screenshot|update_playlist)$')
    command_data: Optional[dict] = Field(default={})
    priority: int = Field(default=5, ge=1, le=10)
    expires_in_minutes: int = Field(default=60, ge=5, le=1440)


class DeviceCommandResponse(BaseModel):
    """Device command response"""
    id: int
    device_id: int
    organization_id: int
    command_type: str
    command_data: dict
    status: str
    priority: int
    sent_at: Optional[datetime]
    executed_at: Optional[datetime]
    failed_at: Optional[datetime]
    result: Optional[dict]
    error_message: Optional[str]
    retry_count: int
    max_retries: int
    created_by: Optional[int]
    created_at: datetime
    updated_at: Optional[datetime]
    expires_at: Optional[datetime]

    class Config:
        from_attributes = True


class PendingCommandsResponse(BaseModel):
    """Pending commands response - for player"""
    commands: list[DeviceCommandResponse]
    count: int


class CommandExecutionRequest(BaseModel):
    """Mark command as executed - from player"""
    result: Optional[dict] = Field(default={"status": "success"})


class CommandFailureRequest(BaseModel):
    """Mark command as failed - from player"""
    error_message: str = Field(..., max_length=500)


# =============================================================================
# DEVICE HEALTH METRICS DTOs
# =============================================================================

class DeviceHealthMetricsCreate(BaseModel):
    """Record health metrics - called by player"""
    # System metrics
    cpu_usage: Optional[float] = Field(None, ge=0, le=100)
    memory_usage: Optional[float] = Field(None, ge=0, le=100)
    memory_total_mb: Optional[int] = Field(None, gt=0)
    memory_used_mb: Optional[int] = Field(None, ge=0)
    disk_usage: Optional[float] = Field(None, ge=0, le=100)
    disk_total_gb: Optional[int] = Field(None, gt=0)
    disk_used_gb: Optional[int] = Field(None, ge=0)

    # Network metrics
    network_latency_ms: Optional[int] = Field(None, ge=0)
    network_download_mbps: Optional[float] = Field(None, ge=0)
    network_upload_mbps: Optional[float] = Field(None, ge=0)

    # Display metrics
    display_resolution: Optional[str] = Field(None, max_length=20)
    display_refresh_rate: Optional[int] = Field(None, gt=0)
    gpu_usage: Optional[float] = Field(None, ge=0, le=100)

    # Player metrics
    player_version: Optional[str] = Field(None, max_length=50)
    player_uptime_hours: Optional[int] = Field(None, ge=0)
    content_errors_count: int = Field(default=0, ge=0)
    last_error_message: Optional[str] = Field(None, max_length=500)

    # Additional metadata
    metadata: Optional[dict] = Field(default={})


class DeviceHealthResponse(BaseModel):
    """Device health response"""
    id: int
    device_id: int
    organization_id: int

    # System metrics
    cpu_usage: Optional[float]
    memory_usage: Optional[float]
    memory_total_mb: Optional[int]
    memory_used_mb: Optional[int]
    disk_usage: Optional[float]
    disk_total_gb: Optional[int]
    disk_used_gb: Optional[int]

    # Network metrics
    network_latency_ms: Optional[int]
    network_download_mbps: Optional[float]
    network_upload_mbps: Optional[float]
    connection_quality: Optional[str]

    # Display metrics
    display_resolution: Optional[str]
    display_refresh_rate: Optional[int]
    gpu_usage: Optional[float]

    # Player metrics
    player_version: Optional[str]
    player_uptime_hours: Optional[int]
    content_errors_count: int
    last_error_message: Optional[str]
    last_error_at: Optional[datetime]

    # Health status
    overall_status: str
    is_alert_triggered: bool
    alert_message: Optional[str]

    # Metadata
    metadata: dict
    recorded_at: datetime

    class Config:
        from_attributes = True


class HealthAlertResponse(BaseModel):
    """Health alert response"""
    alert_type: str
    alert_level: str
    alert_message: str
    metric_value: float
    threshold_value: float
    recorded_at: datetime

    class Config:
        from_attributes = True


class DeviceHealthWithAlertsResponse(BaseModel):
    """Device health with alerts"""
    health: Optional[DeviceHealthResponse]
    alerts: list[HealthAlertResponse]


class HealthHistoryResponse(BaseModel):
    """Health history response"""
    history: list[DeviceHealthResponse]
    count: int


class OrganizationHealthSummaryResponse(BaseModel):
    """Organization health summary"""
    total_devices: int
    healthy_devices: int
    warning_devices: int
    critical_devices: int
    offline_devices: int
    avg_cpu_usage: Optional[float]
    avg_memory_usage: Optional[float]
    avg_disk_usage: Optional[float]
    devices_with_errors: int

    class Config:
        from_attributes = True


# =============================================================================
# DEVICE GROUPS DTOs
# =============================================================================

class CreateDeviceGroupRequest(BaseModel):
    """Create device group - called by CMS"""
    name: str = Field(..., min_length=1, max_length=100)
    description: Optional[str] = Field(None, max_length=500)
    parent_group_id: Optional[int] = Field(None, gt=0)
    group_type: Optional[str] = Field(None, pattern='^(chain|hotel|floor|location|custom)$')
    sort_order: int = Field(default=0, ge=0)
    default_playlist_id: Optional[int] = Field(None, gt=0)


class UpdateDeviceGroupRequest(BaseModel):
    """Update device group - called by CMS"""
    name: Optional[str] = Field(None, min_length=1, max_length=100)
    description: Optional[str] = Field(None, max_length=500)
    parent_group_id: Optional[int] = Field(None, gt=0)
    group_type: Optional[str] = Field(None, pattern='^(chain|hotel|floor|location|custom)$')
    sort_order: Optional[int] = Field(None, ge=0)
    default_playlist_id: Optional[int] = Field(None, gt=0)


class AddDeviceToGroupRequest(BaseModel):
    """Add device to group - called by CMS"""
    device_id: int = Field(..., gt=0)


class RemoveDeviceFromGroupRequest(BaseModel):
    """Remove device from group - called by CMS"""
    device_id: int = Field(..., gt=0)


class DeviceGroupResponse(BaseModel):
    """Device group response"""
    id: int
    name: str
    description: Optional[str]
    parent_group_id: Optional[int]
    organization_id: int
    group_type: Optional[str]
    sort_order: int
    default_playlist_id: Optional[int]
    device_count: int  # Computed field
    parent_name: Optional[str]  # Computed field
    full_path: Optional[str]  # Computed field
    created_by: Optional[int]
    created_at: datetime
    updated_at: Optional[datetime]

    class Config:
        from_attributes = True


class DeviceGroupListResponse(BaseModel):
    """List of device groups"""
    items: list[DeviceGroupResponse]
    total: int

    class Config:
        from_attributes = True


class DeviceGroupStatsResponse(BaseModel):
    """Device group statistics"""
    group_id: int
    total_devices: int
    online_devices: int
    offline_devices: int

    class Config:
        from_attributes = True


class DeviceGroupMemberResponse(BaseModel):
    """Device group member response"""
    id: int
    device_id: int
    group_id: int
    device_name: Optional[str]
    group_name: Optional[str]
    joined_at: datetime
    added_by: Optional[int]

    class Config:
        from_attributes = True


class GroupDevicesResponse(BaseModel):
    """Devices in group response"""
    group_id: int
    devices: list[int]  # List of device IDs
    count: int

    class Config:
        from_attributes = True
