FROM debian:bookworm AS node-builder

RUN apt-get update && \
    apt-get -y install \
        nodejs \
        npm

RUN mkdir -p /app
WORKDIR /app

COPY package.json \
    package-lock.json \
    webpack.prod.js \
    webpack.common.js \
    tsconfig.json \
    /app/
RUN npm install

COPY ./static/sass/*.scss /app/static/sass/
COPY ./static/src/ /app/static/src/
RUN npm run build

# syntax=docker/dockerfile:1.4
# vim: ft=dockerfile

FROM debian:bookworm

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
        build-essential \
        cec-utils \
        curl \
        ffmpeg \
        git \
        git-core \
        ifupdown \
        libcec-dev  \
        libffi-dev \
        libssl-dev \
        libzmq3-dev \
        libzmq5-dev \
        libzmq5 \
        lsb-release \
        mplayer \
        net-tools \
        procps \
        psmisc \
        python3-dev \
        python3-gi \
        python3-pil \
        python3-pip \
        python3-setuptools \
        python3-simplejson \
        python-is-python3 \
        sudo \
        sqlite3

# Works around issue with `curl`
# https://github.com/balena-io-library/base-images/issues/562
RUN c_rehash

# We need this to ensure that the wheels can be built.
# Otherwise we get "invalid command 'bdist_wheel'"
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install --upgrade pip --break-system-packages && \
    pip3 install wheel --break-system-packages

COPY requirements/requirements.txt /tmp/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r /tmp/requirements.txt --break-system-packages

RUN mkdir -p /usr/src/app
COPY . /usr/src/app/
WORKDIR /usr/src/app

COPY --from=node-builder \
    /app/static/dist/ \
    /usr/src/app/static/dist/

ENV GIT_HASH=prod-build-latest
ENV GIT_SHORT_HASH=prod-bf
ENV GIT_BRANCH=production
ENV DEVICE_TYPE=x86

CMD ["bash", "bin/start_server.sh"]