# syntax=docker/dockerfile:1.4
# vim: ft=dockerfile

FROM debian:bookworm

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
        build-essential \
        cec-utils \
        curl \
        ffmpeg \
        git \
        git-core \
        ifupdown \
        libcec-dev  \
        libffi-dev \
        libssl-dev \
        libzmq3-dev \
        libzmq5-dev \
        libzmq5 \
        lsb-release \
        mplayer \
        net-tools \
        procps \
        psmisc \
        python3-dev \
        python3-gi \
        python3-pil \
        python3-pip \
        python3-setuptools \
        python3-simplejson \
        python-is-python3 \
        sudo \
        sqlite3

# Works around issue with `curl`
# https://github.com/balena-io-library/base-images/issues/562
RUN c_rehash

# We need this to ensure that the wheels can be built.
# Otherwise we get "invalid command 'bdist_wheel'"
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install --upgrade pip --break-system-packages && \
    pip3 install wheel --break-system-packages

# vim: ft=dockerfile

# @TODO: Uncomment this build stage when test_add_asset_streaming is fixed.
# FROM debian:buster as builder

# RUN apt-get update && \
#     apt-get -y install --no-install-recommends \
#         build-essential \
#         git \
#         ca-certificates && \
#     apt-get clean

# RUN cd /opt && \
#     git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg && \
#     cd ffmpeg && \
#     git checkout 2ca65fc7b74444edd51d5803a2c1e05a801a6023 && \
#     ./configure --disable-x86asm && make -j$(nproc) --quiet

ENV DEBIAN_FRONTEND noninteractive

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get -y install \
        wget \
        unzip \
        libnss3 \
        libatk1.0-0 \
        libatk-bridge2.0.0 \
        libcups2 \
        libxcomposite1 \
        libxdamage1 \
        nodejs \
        npm

# @TODO: Uncomment the lines below when test_add_asset_streaming is fixed.
# WORKDIR /opt/ffmpeg
# COPY --from=builder /opt/ffmpeg/ffserver ./

ADD requirements/requirements.txt /tmp/requirements.txt
ADD requirements/requirements.dev.txt /tmp/requirements.dev.txt
ADD requirements/requirements.viewer.txt /tmp/requirements.viewer.txt

RUN wget https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.86/linux64/chromedriver-linux64.zip -O /tmp/chromedriver.zip && \
    unzip -o /tmp/chromedriver.zip -d /opt
RUN wget https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.86/linux64/chrome-linux64.zip -O /tmp/chrome.zip && \
    unzip -o /tmp/chrome.zip -d /opt

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install \
        -r /tmp/requirements.txt \
        -r /tmp/requirements.dev.txt \
        -r /tmp/requirements.viewer.txt \
        --break-system-packages

RUN mkdir -p /usr/src/app
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN mkdir -p /data/.screenly /data/screenly_assets
RUN cp ansible/roles/screenly/files/screenly.conf \
    /data/.screenly

ENV GIT_HASH=prod-build-latest
ENV GIT_SHORT_HASH=prod-bf
ENV GIT_BRANCH=production
ENV PATH="/opt/chrome-linux64:/opt/chromedriver-linux64:$PATH"