# vim: ft=dockerfile

FROM debian:bookworm

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        build-essential \
        cec-utils \
        curl \
        ffmpeg \
        git \
        git-core \
        ifupdown \
        libcec-dev  \
        libffi-dev \
        libssl-dev \
        libzmq3-dev \
        libzmq5-dev \
        libzmq5 \
        lsb-release \
        mplayer \
        net-tools \
        procps \
        psmisc \
        python3-dev \
        python3-gi \
        python3-pil \
        python3-pip \
        python3-setuptools \
        python3-simplejson \
        python-is-python3 \
        sudo \
        sqlite3 && \
    rm -rf /var/lib/apt/lists/*

# Works around issue with `curl`
# https://github.com/balena-io-library/base-images/issues/562
RUN c_rehash

# We need this to ensure that the wheels can be built.
# Otherwise we get "invalid command 'bdist_wheel'"
RUN pip3 install --upgrade pip --break-system-packages && \
    pip3 install wheel --break-system-packages

COPY requirements/requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt --break-system-packages

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/

ENV GIT_HASH=prod-build-latest
ENV GIT_SHORT_HASH=prod-bf
ENV GIT_BRANCH=production
ENV DJANGO_SETTINGS_MODULE="anthias_django.settings"

CMD celery -A celery_tasks.celery worker \
  -B -n worker@anthias \
  --loglevel=info \
  --schedule \
  /tmp/celerybeat-schedule