# vim: ft=dockerfile

FROM debian:bookworm

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        nginx && \
    rm -rf /var/lib/apt/lists/*

ENV GIT_HASH=prod-build-latest
ENV GIT_SHORT_HASH=prod-bf
ENV GIT_BRANCH=production

RUN rm -f /etc/nginx/sites-enabled/default
COPY docker/nginx/nginx.production.conf /etc/nginx/sites-enabled/anthias.conf

CMD ["nginx", "-g", "daemon off;"]
