# syntax=docker/dockerfile:1.4
# vim: ft=dockerfile

FROM debian:bookworm

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
    redis-server

ENV GIT_HASH=prod-build-latest
ENV GIT_SHORT_HASH=prod-bf
ENV GIT_BRANCH=production

RUN sed -i 's/^bind.*/bind 0.0.0.0/g' /etc/redis/redis.conf
RUN sed -i 's/^protected-mode.*/protected-mode no/g' /etc/redis/redis.conf

CMD ["redis-server", "--protected-mode", "no"]
