# syntax=docker/dockerfile:1.4
# vim: ft=dockerfile

FROM debian:bookworm

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get -y install --no-install-recommends \
        build-essential \
        cec-utils \
        curl \
        ffmpeg \
        git \
        git-core \
        ifupdown \
        libcec-dev  \
        libffi-dev \
        libssl-dev \
        libzmq3-dev \
        libzmq5-dev \
        libzmq5 \
        lsb-release \
        mplayer \
        net-tools \
        procps \
        psmisc \
        python3-dev \
        python3-gi \
        python3-pil \
        python3-pip \
        python3-setuptools \
        python3-simplejson \
        python-is-python3 \
        sudo \
        sqlite3

# Works around issue with `curl`
# https://github.com/balena-io-library/base-images/issues/562
RUN c_rehash

# We need this to ensure that the wheels can be built.
# Otherwise we get "invalid command 'bdist_wheel'"
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install --upgrade pip --break-system-packages && \
    pip3 install wheel --break-system-packages

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get -y install --no-install-recommends \
        dnsmasq \
        iw \
        network-manager \
        unzip \
        wget \
        wireless-tools

WORKDIR /usr/src/app

# @TODO: WiFi Connect 4.11.1 doesn't have a release for Raspberry Pi
#        devices that has ARMv6 support. We should remove this once a
#        new compatible release is available.
RUN if [[ ! -z "https://github.com/balena-os/wifi-connect/releases/download/v4.11.1/wifi-connect-v4.11.1-linux-amd64.zip" ]]; then \
    curl -sL -o /tmp/wifi_connect.zip "https://github.com/balena-os/wifi-connect/releases/download/v4.11.1/wifi-connect-v4.11.1-linux-amd64.zip" && \
    unzip -o /tmp/wifi_connect.zip -d /usr/src/app && \
    rm /tmp/wifi_connect.zip; fi

COPY requirements/requirements.wifi-connect.txt /tmp/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r /tmp/requirements.txt --break-system-packages

COPY send_zmq_message.py ./

RUN touch /var/lib/misc/dnsmasq.leases

COPY bin/start_wifi_connect.sh ./

ENV DEVICE_TYPE=x86
ENV GIT_HASH=prod-build-latest
ENV GIT_SHORT_HASH=prod-bf
ENV GIT_BRANCH=production

CMD ["bash", "start_wifi_connect.sh"]