/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "ATLAS PUGUH Documentation",
  "tagline": "Constitutional Law System for AI Decisions",
  "favicon": "img/favicon.ico",
  "url": "https://docs.puguh.atlashub.com",
  "baseUrl": "/",
  "organizationName": "atlashub",
  "projectName": "puguh-docs",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/mnt/f/WINDSURF/neliti_code/signate/ATLAS_PUGUH/docs-site/sidebars.js",
          "editUrl": "https://github.com/atlashub/puguh/tree/main/docs-site/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "blog": {
          "showReadingTime": true,
          "blogTitle": "Changelog",
          "blogDescription": "Latest updates and releases for ATLAS PUGUH",
          "postsPerPage": 10,
          "editUrl": "https://github.com/atlashub/puguh/tree/main/docs-site/"
        },
        "theme": {
          "customCss": "/mnt/f/WINDSURF/neliti_code/signate/ATLAS_PUGUH/docs-site/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/puguh-social-card.png",
    "navbar": {
      "title": "PUGUH Docs",
      "logo": {
        "alt": "ATLAS PUGUH Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Documentation"
        },
        {
          "to": "/blog",
          "label": "Changelog",
          "position": "left"
        },
        {
          "href": "https://admin-puguh.atlashub.com",
          "label": "Go to App",
          "position": "right"
        },
        {
          "href": "https://github.com/atlashub/puguh",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/getting-started/quick-start"
            },
            {
              "label": "User Guides",
              "to": "/docs/user-guides/iam/users"
            },
            {
              "label": "API Reference",
              "to": "/docs/api-reference/authentication"
            }
          ]
        },
        {
          "title": "Product",
          "items": [
            {
              "label": "Dashboard",
              "href": "https://admin-puguh.atlashub.com"
            },
            {
              "label": "Pricing",
              "href": "https://admin-puguh.atlashub.com/pricing"
            },
            {
              "label": "Status",
              "href": "https://status.atlashub.com"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "About",
              "href": "https://atlashub.com/about"
            },
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "Contact",
              "href": "https://atlashub.com/contact"
            }
          ]
        }
      ],
      "copyright": "Copyright 2026 ATLAS PUGUH. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "python",
        "typescript"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "support_us",
      "content": "New to PUGUH? Check out our <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"/docs/getting-started/quick-start\">Quick Start Guide</a>!",
      "backgroundColor": "#f59e0b",
      "textColor": "#1f2937",
      "isCloseable": true
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
