#!/bin/bash
export TZ=Asia/Jakarta

# Change to working directory
cd /opt/backend/webos

# Execute the application with timestamp logging
exec /opt/backend/webos/server-linux 2>&1 | while IFS= read -r line; do
    echo "$(date '+%Y-%m-%d %H:%M:%S') [BACKEND] $line" >> /opt/backend/webos/logs/backend.log
done
